<?xml version="1.0" ?>
<wfs:FeatureCollection xmlns:gsmlgt="http://www.opengis.net/gsml/4.1/GeologicTime" xmlns:gsmlb="http://www.opengis.net/gsml/4.1/GeoSciML-Basic" xmlns:gsmlla="http://www.opengis.net/gsml/4.1/LaboratoryAnalysis-Specimen" xmlns:gsml="http://www.opengis.net/gsml/4.1/GeoSciML" xmlns:gsmlbh="http://www.opengis.net/gsml/4.1/Borehole" xmlns:gsmle="http://www.opengis.net/gsml/4.1/GeoSciML-Extension" xmlns:swe="http://www.opengis.net/swe/2.0" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:gmlexr="http://www.opengis.net/gml/3.3/exr" xmlns:sam="http://www.opengis.net/sampling/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ns1="http://www.w3.org/1999/xhtml" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gss="http://www.isotc211.org/2005/gss" xmlns:gsr="http://www.isotc211.org/2005/gsr" xmlns:gts="http://www.isotc211.org/2005/gts" xmlns:om="http://www.opengis.net/om/2.0" xmlns:sf="http://www.opengis.net/samplingSpatial/2.0" xmlns:cit="http://standards.iso.org/iso/19115/-3/cit/1.0" xmlns:mcc="http://standards.iso.org/iso/19115/-3/mcc/1.0" xmlns:ns2="http://standards.iso.org/iso/19115/-3/gco/1.0" xmlns:mrl="http://standards.iso.org/iso/19115/-3/mrl/1.0" xmlns:spec="http://www.opengis.net/samplingSpecimen/2.0" xmlns:hfp="http://www.w3.org/2001/XMLSchema-hasFacetAndProperty" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wfs="http://www.opengis.net/wfs/2.0" xsi:schemaLocation="http://www.opengis.net/gsml/4.1/GeoSciML http://schemas.opengis.net/gsml/4.1/geosciml.xsd http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd" numberMatched="5703" numberReturned="5703" timeStamp="2023-02-23T07:36:37.622+01:00">
  <wfs:member>
    <gsmlb:NaturalGeomorphologicFeature gml:id="NaturalGeomorphologicFeature_B7730E59-8464-471D-84CD-7EA7599155F5">
      <gsmlb:naturalGeomorphologicFeatureType xlink:href="http://inspire.ec.europa.eu/codelist/NaturalGeomorphologicFeatureTypeValue/hill"></gsmlb:naturalGeomorphologicFeatureType>
      <gsmlb:activity xlink:href="http://inspire.ec.europa.eu/codelist/GeomorphologicActivityValue/inactive" xlink:title="inactive"></gsmlb:activity>
    </gsmlb:NaturalGeomorphologicFeature>
  </wfs:member>
</wfs:FeatureCollection>
